#!/usr/bin/env python3
"""Self-host the two Google fonts the web tool uses, latin subsets only.

The tool's natural habitat is a bench with no wifi, and a CDN font request was
the only thing making first paint depend on the network. Run this once; commit
`web/fonts/` and `web/fonts.css`.

    python3 tools/fetch_fonts.py
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "web"
FONT_DIR = WEB / "fonts"

CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=DM+Sans:ital,opsz,wght@0,9..40,500;0,9..40,700;1,9..40,500"
    "&family=JetBrains+Mono:wght@400;600&display=swap"
)
# A woff2-capable desktop UA; without it Google serves the legacy ttf CSS.
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
)
KEEP_SUBSETS = {"latin", "latin-ext"}

HEADER = """/* Self-hosted subset of the two Google fonts, latin + latin-ext only.
   Generated by tools/fetch_fonts.py — edit that, not this. */

"""


def fetch(url: str) -> bytes:
    result = subprocess.run(
        ["curl", "-fsSL", "-A", UA, url], capture_output=True, timeout=60
    )
    if result.returncode != 0:
        raise SystemExit(f"curl failed for {url}: {result.stderr.decode().strip()}")
    return result.stdout


def main() -> None:
    css = fetch(CSS_URL).decode()
    blocks = re.findall(r"/\*\s*([\w\[\]-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
    if not blocks:
        raise SystemExit("no @font-face blocks parsed — did the CSS format change?")

    FONT_DIR.mkdir(exist_ok=True)
    for stale in FONT_DIR.glob("*.woff2"):
        stale.unlink()

    faces, total = [], 0
    for subset, block in blocks:
        if subset not in KEEP_SUBSETS:
            continue
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*([^;]+);", block).group(1).strip()
        style = re.search(r"font-style:\s*([^;]+);", block).group(1).strip()
        stem = f"{family}-{style}-{weight}-{subset}".lower()
        stem = re.sub(r"[^a-z0-9.-]+", "-", stem).replace("..", "-")
        name = f"{stem}.woff2"

        data = fetch(url)
        (FONT_DIR / name).write_bytes(data)
        total += len(data)
        faces.append(block.replace(url, f"./fonts/{name}"))
        print(f"  {name}  {len(data) / 1024:.0f} KB")

    if not faces:
        raise SystemExit("nothing kept — KEEP_SUBSETS matched no blocks")

    (WEB / "fonts.css").write_text(HEADER + "\n\n".join(faces) + "\n")
    print(f"{len(faces)} faces, {total / 1024:.0f} KB → web/fonts.css")


if __name__ == "__main__":
    sys.exit(main())
